name: Deploy VPC to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install AWS CDK and Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aws-cdk-lib constructs
          npm install -g aws-cdk

      - name: Install Project Dependencies
        run: |
          pip install -r requirements.txt

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change to your desired AWS region

      - name: Bootstrap AWS CDK (if needed)
        run: cdk bootstrap

      - name: Synthesize CDK Stack
        run: cdk synth

      - name: Deploy CDK Stack
        run: cdk deploy --require-approval never
